config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'movies#index'

  resources :movies
  get 'movies/:id/rate', to: 'movies#do_rate', :as => "movie_rate"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  enum category: { action: "action", drama: "drama", romace: "romance", scientific: "scientific" }
  belongs_to :user

  has_many :user_ratings

  validates :title, presence: true, uniqueness: true

  def self.search(params)
    movies = all
    movies = movies.where("lower(title) LIKE ?", "%#{params[:search].downcase}%").or(movies.where("lower(text) LIKE ?", "%#{params[:search].downcase}%")) if params[:search]
    movies = movies.where("category = ?", params[:category]) if params[:category]
    movies = movies.where("ROUND(average_rating) = ?", "#{params[:average_rating]}") if params[:average_rating]
    movies
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_ratings
  has_many :movies

  validates :email, presence: true, uniqueness: true
end

app/models/user_rating.rb
class UserRating < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  after_save do
    movie.update_attribute(:average_rating, movie.user_ratings.average("user_ratings.rate"))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy, :do_rate]
  before_action :authenticate_user!, :except => [:index, :show]

  # GET /movies
  # GET /movies.json
  def index
    @categories_count = Hash[Movie.group(:category).count.sort_by {|_key, value| value}.reverse]
    @ratings_count = Movie.group("Round(average_rating)").count
    @movies = Movie.search(params).order(title: :desc).paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html
      format.json { render :json => @movies }
    end
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.create(movie_params)

    if @movie.save
      flash[:notice] = "Movie was successfully created."
      respond_to do |format|
        format.html { redirect_to movies_url }
        format.json { head :no_content }
      end
    else
      flash.now[:error] = "Movie couldn't be created."
      respond_to do |format|
        format.html { render :nds }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    if @movie.update(movie_params)
        flash[:notice] = "Movie was successfully updated."
        respond_to do |format|
          format.html { redirect_to movies_url }
          format.json { head :no_content }
        end
      else
        flash[:notice] = "Movie couldn't be updated."
        respond_to do |format|
          format.html { render :edit }
          format.json { render json: @movie.errors, status: :unprocessable_entity }
        end
      end
  end

  # GET /movies/1/rate.json
  def do_rate
    if !params[:rate] || params[:rate].to_i > 5 || params[:rate].to_i < 0
        respond_to do |format|
            format.json { render :json => 'please select valid rate' }
        end

    else

        @rating = UserRating.where(user: current_user, movie: @movie)
        if !@rating.exists?
            @rating = UserRating.create({user: current_user, movie: @movie, rate: params[:rate]})
        else
            @rating.update({rate: params[:rate]})
        end
        respond_to do |format|
          @movie = Movie.find(params[:id])
          format.json { render :json => @movie }
        end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    flash[:notice] = "Movie was successfully destroyed."
    respond_to do |format|
      format.html { redirect_to movies_url }
      format.json { head :no_content }
    end
  end

  private

    def set_movie
      @movie = Movie.find(params[:id])
    end

    def movie_params
      params.require(:movie).permit(:title, :text, :category, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)

    if @user.save
      flash[:notice] = "User was successfully registered.."
      redirect_to login_url
    else
      flash.now[:error] = "User couldn't be registered"
      render action: "new"
    end
  end

  private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moviedb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>

    <nav class="navbar navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header">
            <% if user_signed_in? %>
              Logged in as <strong><%= current_user.email %></strong>.
              <%= link_to "Logout", destroy_user_session_path, :method => :delete, :class => 'navbar-link'  %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
              <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
            <% end %>
        </div>
      </div>
    </nav>

    <div id="main-container" class="container">
        <div class="offset-3">
            <% flash.each do |name, msg| -%>
              <%= content_tag :div, msg, class: (name == 'alert' ? 'alert alert-danger' : 'alert alert-success') %>
            <% end -%>
        </div>

        <div id="content" class="row">
            <%= yield %>
        </div>
    </div>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for movie, url: movie.new_record? ? movies_path : movie_path(id: movie) do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Title</label>
    <%= f.text_field :title, :class => 'form-control col-sm-10' %>
  </div>
  <div class="form-group row">
   <label class="col-sm-2 col-form-label">Text</label>
   <%= f.text_field :text, :class => 'form-control col-sm-10' %>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Category</label>
    <%= f.select :category, Movie.categories, {}, :class => 'form-control col-sm-10'  %>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
<% end %>

app/views/movies/_star_rating.html.erb
<star-rating v-model="rating" data-score=<%= rating %> v-bind:read-only="true" v-bind:star-size="30" v-bind:show-rating="false"></star-rating>
<script>
    /*new Vue({
        el: 'star-rating',
        data: {
            rating: <%= rating %>
        }
    });*/
</script>

app/views/movies/edit.html.erb
<div class="col-md-9 offset-3">
    <h1>Edit Movie</h1>

    <%= render 'form', movie: @movie %>
</div>

app/views/movies/index.html.erb
<aside class="col-sm-3">
  <div class="card">
	<article class="card-group-item">
		<header class="card-header"><h6 class="title"><a href="<%= "?" %>">All</a></h6></header>
    </article>
    <article class="card-group-item">
		<header class="card-header"><h6 class="title">Category </h6></header>
		<div class="filter-content">
			<div class="list-group list-group-flush">
			  <% Hash[Movie.categories].each do |i, category| %>
                <a href="<%= "?category=#{category}" %>" class="list-group-item"><%= category %> <span class="float-right badge badge-light round"><%= @categories_count[category] ? @categories_count[category] : 0 %></span> </a>
              <% end %>
			</div>
		</div>
	</article>

	<article class="card-group-item">
		<header class="card-header"><h6 class="title">Rating </h6></header>
		<div class="filter-content">
			<div class="list-group list-group-flush">
			  <% (5).downto(0).each do |c| %>
                <a href="<%= "?average_rating=#{c}" %>" class="list-group-item">
                  <div class="reviews">
                    <star-rating class="star-rating" v-bind:rating=<%= c.to_i %> v-bind:read-only="true" v-bind:star-size="30" v-bind:show-rating="false"></star-rating>
                  </div>
                  <span class="float-right badge badge-light round"><%= @ratings_count[c.to_f] ? @ratings_count[c.to_f] : 0 %></span>
                </a>
              <% end %>
			</div>
		</div>
	</article>
  </div>
</aside>

<div class="col-md-9">
    <h1>Movies</h1>

    <div class="mx-sm-4 mb-3 float-right"><%= link_to 'Add Movie', new_movie_path %></div>
    <%= form_tag movies_path, :class => 'form-inline', method: :get do %>
      <div class="form-group mx-sm-4 mb-2">
        <%= text_field_tag :search, params[:search], :class => 'form-control' %>
      </div>
      <button type="button" onclick="Turbolinks.visit('?search='+$('#search').val())" class="btn btn-primary mb-2">Search</button>
    <% end %>

    <% if !@movies.empty? %>
    <table class="table">
        <thead>
          <tr>
            <th>Title</th>
            <th>Text</th>
            <th>Category</th>
            <th>Average Rating</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        <% @movies.each do |movie| %>
          <tr>
            <td><%= movie.title %></td>
            <td><%= movie.text %></td>
            <td><%= movie.category %></td>
            <td><star-rating class="star-rating" v-bind:rating=<%= movie.average_rating %> v-bind:read-only="true" v-bind:increment=0.1 v-bind:star-size="30" ></star-rating></td>
            <% if user_signed_in? && movie.user == current_user %>
            <td>
                <%= link_to 'Edit', edit_movie_path(movie) %>
                <%= link_to 'Remove', movie_path(movie), method: :delete %>
            </td>
            <% else %>
            <td>
                <% if user_signed_in? %>
                   <% userRating = UserRating.where(user: current_user, movie: movie) %>
                  <star-rating class="star-rating" v-bind:rating=<%= (userRating.exists? ? userRating.first.rate : 0) %> @rating-selected="setRating($event, <%= movie.id %>)" v-bind:star-size="30" v-bind:show-rating="false"></star-rating>
                <% end %>
                <%= link_to 'Show', movie_path(movie) %>
            </td>
            <% end %>
          </tr>
        <% end %>
        </tbody>
    </table>
    <% else %>
    No Movies Found!
    <% end %>

    <%= will_paginate(@movies, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
</div>

app/views/movies/new.html.erb
<div class="col-md-9 offset-3">
    <h1>New Movie</h1>

    <%= render 'form', movie: @movie %>
</div>

app/views/movies/show.html.erb
<div class="col-md-9 offset-3">
    <p><label>Category:</label> <%= @movie.category %></p>
    <p><label>Title:</label> <%= @movie.title %></p>
    <p><label>Text:</label> <%= @movie.text %></p>
</div>